import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repo of this plugin
*/
`;

const prod = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

/** @type {import("esbuild").BuildOptions} */
let options = {
	bundle: true,
	entryPoints: ["src/main.ts"],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	// docs/使用说明.md 以纯文本内联进包：生成《使用说明.md》时从代码中恢复（独立文档维护，见 src/usage_guide_default.ts）
	loader: { ".md": "text" },
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "release/main.js",
	banner: { js: banner },
};

fs.mkdirSync("release", { recursive: true }); // 编译产物统一放 release/（该目录已 gitignore，不入库）
// release/ 即可分发目录：把非编译但插件必需的文件一并拷入。写作指南 WRITING_GUIDE.md 不再随包发布——其文本已由 .md=text 内联进 main.js（见 src/system_guide_default.ts），首启由运行时播种系统级文件；移出 release/ 以通过社区校验器「无额外不支持文件」检查
for (const f of ["manifest.json", "styles.css"]) fs.copyFileSync(f, `release/${f}`);

if (watch) {
	const ctx = await esbuild.context(options);
	await ctx.watch();
} else {
	await esbuild.build(options);
	fs.mkdirSync("dist", { recursive: true }); // 社区目录校验器在仓库根/dist/build/out 查找构建产物 main.js，这里同步一份（同样 gitignore）
	fs.copyFileSync("release/main.js", "dist/main.js");
	process.exit(0);
}
